### ISSUE TITLE
Didn't work (for the moment) 

### ISSUE THREAD

**Issue by mathvos** [csu333/Surrogate#1]
I have enabled the module, 
I think I have activate the rule but not sure. 

I have already the message from db application who tell me for security blablabla.. 

But thank you for your module by the way ;-)

![screenshot_20170119-192242](https://cloud.githubusercontent.com/assets/25228711/22119669/bc16afa8-de7c-11e6-9f4e-b45c8a80b8dd.png)
![screenshot_20170119-192218](https://cloud.githubusercontent.com/assets/25228711/22119674/bf9f9018-de7c-11e6-8dd6-eb1b5f64e52f.png)

**Comment by csu333** [comment]
My pleasure 😉

Thank you for the nice report. I see what's wrong at first sight: the application is not enabled. You need to click on the sync icon (the double rounded arrows which are crossed on your first screenshot) and save. The application should then appear black instead on grey in the list of your second screenshot. 

I realize that the icon is not the best I could pick but I didn't find any better one so I'm open for suggestion.

**Comment by mathvos** [comment]
Thank you, that works now. 

Maybe an simple icon with only on/off showed?

And sorry for my worth english by the way.

**Comment by csu333** [comment]
It was too obvious :-p It's fixed now. 

Thank you
