### ISSUE TITLE
pokemon go rule

### ISSUE THREAD

**Issue by melchisedekko** [csu333/Surrogate#11]
I'm really not an expert by any means, so I apologize if i'm not clear or If i make some silly mistakes. I looking for some help to set a rule to avoid the pokemong go app to check if the phone is rooted. I'm Not sure if what i'm doing is correct. Please see the attachments
[DeviceBlockProvider.txt](https://github.com/csu333/Surrogate/files/1106335/DeviceBlockProvider.txt)
[DeviceBlockProvider.smali.txt](https://github.com/csu333/Surrogate/files/1106339/DeviceBlockProvider.smali.txt)

![rule](https://user-images.githubusercontent.com/10241980/27602286-924c0592-5b72-11e7-95d7-0493350ef68b.png)

**Comment by circleous** [comment]
The packagename is `com.nianticlabs.pokemongo`. I dont know Java interpretation of Boolean, but i believe its not as a String.
EDIT: Boolean => `java.lang.Boolean`, maybe.
