### ISSUE TITLE
App crash/force close

### ISSUE THREAD

**Issue by w0rinal** [csu333/Surrogate#3]
I found a bug (1.1b3), which seems fairly easily reproducible.
Open the app, click a package, click a rule, then click the copy button, press back and again click a rule, then the app force closes and restarts.

The log attached has been taken with Scoop xposed module, let me know if you need any further information.
Regards
[Surrogate_1.1b3.zip](https://github.com/csu333/Surrogate/files/733022/Surrogate_1.1b3.zip)

**Comment by csu333** [comment]
I must be too lazy :-p It's fixed in latest release.

Thank you for reporting (and for your pull request as well )
