### ISSUE TITLE
Import/Export ruleset locally

### ISSUE THREAD

**Issue by circleous** [csu333/Surrogate#6]

**Comment by csu333** [comment]
Exporting is actually already possible by sharing to a file explorer app like "ES File Explorer" or "File Expert" but importing looks important indeed. I just have to find a good file picker.

**Comment by csu333** [comment]
Added ability to import from file in b6214adede799ddaccc74e13627a38d6c680a433
Now I just have to post a (beta) build 1.1b5 on Xposed repository
