### ISSUE TITLE
Keytrade bank app not working anymore

### ISSUE THREAD

**Issue by csu333** [csu333/Surrogate#9]
Keytrade bank app detects root again

**Comment by csu333** [comment]
Hello @Hoolite,

The method name is changed: instead of "k", it has become "j". You can either change the rule yourself or download the new one. You have to delete the existing package for Keytrade first then "import rule from internet".

Best regards,

**Comment by ghost** [comment]
Hi @csu333,
Thank you for looking into this. Much appreciated! I am now able to create a softkey, well, almost able to create one. The app crashes at final step when I need to scan a Qr code. Not sure what's causing this.

Kind regards,

**Comment by csu333** [comment]
Unfortunately, I don't have a Keytrade account so I can't get that far. To get more information, I would need some logcat. Since your phone is rooted, I guess you could have the requirements already met. You need to: 
1. Have the Android driver installed (or use Linux)
2. Enable "debug mode"
3. Have the "adb" software at your disposal

In command line, having your phone connected to an USB port, you can get a whole lot of logging by launching the command: `adb logcat` You'll see a lot of text going through your screen. When getting the QR code error, you should see the Exception causing the application to crash. This could help me figure out what's the issue there.

If you used KingoRoot or anything like that and that you don't have all the adb stuff, you can still use application like Logcat on your Android device which will just do the same but you have to be a little bit faster switching application because the log is erased pretty quickly.

**Comment by ghost** [comment]
Hi @csu333,

Thank you for wanting to look in to this. I used the app 'Catlog' to make a log. I hope you can do something with this.

(I cleared log before I started with adding a softkey in the app and quickly pauzed if after the error)

Edit; uploaded text file.

[2017-04-22-13-37-44.txt](https://github.com/csu333/Surrogate/files/948944/2017-04-22-13-37-44.txt)

**Comment by csu333** [comment]
Oh I see. I didn't though that the new «k» method would have the same signature. Just delete it from the Keytrade package in Surrogate and it should be fine (after killing the Keytrade application). 


Le 22 avr. 2017 13:49, à 13:49, Hoolite <notifications@github.com> a écrit:

**Comment by ghost** [comment]
Hi @csu333,
 I'm sorry, I don't completely understand. If I erase the 'k' as method name and save it again, then the softkey isn't available anymore. I'm probably doing it wrong. Sorry. 

Kind regards,

**Comment by csu333** [comment]
I realize I haven't been to precise and you probably ended up deleting the whole package. So first, you need to reload the rule set from internet again and make sure you can see the Keytrade entry in the app list of Surrogate. 

Once you have, click on it. You'll have a screen showing the package name and a list of rules. There should be 2 of them. If my assumption is correct, click on the one showing «Method: k», click on delete then save.

If you only have one, make sure the method is «j». If it shows «k», click on the rule, change the method name to «j» then save twice. Make sure the rule is enabled and it should be fine (hopefully).

Le 22 avr. 2017 17:33, à 17:33, Hoolite <notifications@github.com> a écrit:

**Comment by ghost** [comment]
Hi @csu333,

Thank you very much for making it more clear. This really did the trick. I can't thank you enough for your mobility and support. Thank you for making it possible to bypass detection.

Kind regards,
